
import React, { useState } from 'react';
import { useAppContext } from '../hooks/useAppContext';
import { User } from '../types';
import { UserIcon } from './Icons';
import { loginWithGoogle, getFacebookLoginUrl } from '../services/authService';

// Mock Social Icon components for visual representation
const GoogleIcon = () => <svg viewBox="0 0 48 48" className="w-6 h-6"><path fill="#FFC107" d="M43.611 20.083H42V20H24v8h11.303c-1.649 4.657-6.08 8-11.303 8c-6.627 0-12-5.373-12-12s5.373-12 12-12c3.059 0 5.842 1.154 7.961 3.039l5.657-5.657C34.046 6.053 29.268 4 24 4C12.955 4 4 12.955 4 24s8.955 20 20 20s20-8.955 20-20c0-1.341-.138-2.65-.389-3.917z"></path><path fill="#FF3D00" d="M6.306 14.691l6.571 4.819C14.655 15.108 18.961 12 24 12c3.059 0 5.842 1.154 7.961 3.039l5.657-5.657C34.046 6.053 29.268 4 24 4C16.318 4 9.656 8.337 6.306 14.691z"></path><path fill="#4CAF50" d="M24 44c5.166 0 9.86-1.97 13.091-5.192l-6.19-4.821c-1.999 1.34-4.484 2.17-7.201 2.17-5.595 0-10.31-3.6-11.97-8.62H4.909v5.034C8.173 39.043 15.574 44 24 44z"></path><path fill="#1976D2" d="M43.611 20.083H42V20H24v8h11.303c-.792 2.237-2.231 4.16-4.082 5.571l6.19 4.821C40.636 35.14 44 28.728 44 24c0-1.341-.138-2.65-.389-3.917z"></path></svg>;
const FacebookIcon = () => <svg viewBox="0 0 24 24" className="w-6 h-6" fill="#1877F2"><path d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878V14.89h-2.87v-2.782h2.87V9.787c0-2.843 1.693-4.417 4.31-4.417 1.232 0 2.5.223 2.5.223v2.37h-1.218c-1.42 0-1.85.86-1.85 1.743v2.093h3.18l-.51 2.782h-2.67v7.008C18.343 21.128 22 16.991 22 12z"></path></svg>;

const Spinner = () => (
    <svg className="animate-spin h-6 w-6 text-brand-pink" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
);

type PendingUser = Omit<User, 'verificationStatus' | 'purchaseHistory' | 'verificationDetails' | 'favorites' | 'notifications'>;

const LoginModal: React.FC = () => {
    const { closeLoginModal, login, register, addNotification } = useAppContext();
    const [mode, setMode] = useState<'login' | 'register'>('login');
    const [step, setStep] = useState<'details' | 'social_confirm' | 'age'>('details');
    const [isSocialLoading, setIsSocialLoading] = useState<null | 'Google' | 'Facebook'>(null);
    
    // Form state
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    
    // Registration-specific state
    const [pendingUser, setPendingUser] = useState<PendingUser | null>(null);
    const [dob, setDob] = useState({ day: '', month: '', year: '' });
    const [dobError, setDobError] = useState<string | null>(null);

    const resetFormState = () => {
        setName('');
        setEmail('');
        setPassword('');
        setPendingUser(null);
        setDob({ day: '', month: '', year: '' });
        setDobError(null);
        setStep('details');
    };

    const handleLoginSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        const success = login({ email });
        if (!success) {
            addNotification('Invalid credentials or user not found.', 'error');
        }
    };
    
    const handleRegisterDetailsSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!name || !email || !password) {
            addNotification('Please fill in all fields.', 'error');
            return;
        }
        
        const userData: PendingUser = { name, email, profilePic: null };
        setPendingUser(userData);
        setStep('age');
    };
    
    const handleSocialLogin = async (provider: 'Google' | 'Facebook') => {
        setIsSocialLoading(provider);

        if (provider === 'Facebook') {
            // This is the real OAuth 2.0 flow.
            // Redirect the user to the URL generated by our service,
            // which points to our backend. The backend handles the secure
            // communication with Facebook.
            window.location.href = getFacebookLoginUrl();
            return; // The page will redirect, so no more code will execute here.
        }

        // --- Google Login (Mock) ---
        // This simulates the flow AFTER the user returns from Google and our
        // backend has fetched their data.
        try {
            // The Google flow is currently mocked. A real implementation would be similar to Facebook's.
            const userProfile = await loginWithGoogle(); // Using mock for now
            
            setPendingUser(userProfile);
            setStep('social_confirm');
        } catch (error) {
            console.error(`${provider} login failed:`, error);
            addNotification(`Failed to connect with ${provider}. Please try again.`, 'error');
        } finally {
            setIsSocialLoading(null);
        }
    };

    const handleAgeVerification = () => {
        const { day, month, year } = dob;
        if (!day || !month || !year || day.length > 2 || month.length > 2 || year.length !== 4) {
            setDobError('Please enter a valid date of birth (DD/MM/YYYY).');
            return;
        }

        const dayNum = parseInt(day, 10);
        const monthNum = parseInt(month, 10);
        const yearNum = parseInt(year, 10);

        if (isNaN(dayNum) || isNaN(monthNum) || isNaN(yearNum) || monthNum < 1 || monthNum > 12 || dayNum < 1 || dayNum > 31) {
            setDobError('Please enter a valid date.');
            return;
        }

        const birthDate = new Date(yearNum, monthNum - 1, dayNum);
        if (birthDate.getFullYear() !== yearNum || birthDate.getMonth() !== monthNum - 1 || birthDate.getDate() !== dayNum) {
            setDobError('Please enter a valid date.');
            return;
        }
        
        const today = new Date();
        let age = today.getFullYear() - birthDate.getFullYear();
        const m = today.getMonth() - birthDate.getMonth();
        if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
            age--;
        }

        if (age >= 18) {
            setDobError(null);
            if (pendingUser) {
                register(pendingUser); // Use the register function
            } else {
                addNotification('An error occurred. Please try again.', 'error');
                setStep('details');
            }
        } else if (age < 0) {
            setDobError('Please enter a date in the past.');
        } else {
            setDobError('You must be at least 18 years old to register.');
        }
    };

    const handleModalContentClick = (e: React.MouseEvent) => {
        e.stopPropagation();
    };
    
    const handleSwitchMode = (newMode: 'login' | 'register') => {
        resetFormState();
        setMode(newMode);
    };

    const SocialButtons = () => (
        <div className="space-y-3">
            <button 
                onClick={() => handleSocialLogin('Google')} 
                disabled={isSocialLoading !== null}
                className="w-full inline-flex items-center justify-center p-3 border border-gray-300 rounded-md hover:bg-gray-50 transition disabled:opacity-50"
            >
                {isSocialLoading === 'Google' ? (
                    <Spinner />
                ) : (
                    <>
                        <GoogleIcon />
                        <span className="ml-3 font-medium text-gray-700">Continue with Google</span>
                    </>
                )}
            </button>
            <button 
                onClick={() => handleSocialLogin('Facebook')} 
                disabled={isSocialLoading !== null}
                className="w-full inline-flex items-center justify-center p-3 border border-gray-300 rounded-md hover:bg-gray-50 transition disabled:opacity-50"
            >
                {isSocialLoading === 'Facebook' ? (
                    <Spinner />
                ) : (
                    <>
                        <FacebookIcon />
                        <span className="ml-3 font-medium text-gray-700">Continue with Facebook</span>
                    </>
                )}
            </button>
        </div>
    );

    const OrSeparator = () => (
        <div className="my-6 flex items-center">
            <div className="flex-grow border-t border-gray-200"></div>
            <span className="flex-shrink mx-4 text-gray-400 font-medium text-sm">OR</span>
            <div className="flex-grow border-t border-gray-200"></div>
        </div>
    );
    
    const renderLoginView = () => (
        <>
            <div className="text-center">
                <h2 className="text-3xl font-bold text-brand-pink">Welcome Back</h2>
                <p className="text-gray-600 mt-2">Log in to continue to AURA.</p>
            </div>
            <div className="mt-8">
                <SocialButtons />
                <OrSeparator />
                <form onSubmit={handleLoginSubmit} className="space-y-4">
                    <input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email Address" required className="w-full p-3 bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    <input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" required className="w-full p-3 bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    <button type="submit" className="w-full bg-brand-pink hover:bg-brand-pink-hover text-white font-bold py-3 px-6 rounded-lg transition duration-300">
                        Log In
                    </button>
                </form>
            </div>
            <p className="text-center text-sm text-gray-500 mt-6">
                Don't have an account?{' '}
                <button onClick={() => handleSwitchMode('register')} className="font-semibold text-brand-pink hover:underline">
                    Sign up
                </button>
            </p>
        </>
    );

    const renderRegisterView = () => (
        <>
            <div className="text-center">
                <h2 className="text-3xl font-bold text-brand-pink">Create Your Account</h2>
                <p className="text-gray-600 mt-2">Join AURA to connect with our models.</p>
            </div>
            
            <div className="mt-8">
                <SocialButtons />
                <OrSeparator />
                <form onSubmit={handleRegisterDetailsSubmit} className="space-y-4">
                    <input id="name" type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your Name" required className="w-full p-3 bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    <input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email Address" required className="w-full p-3 bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    <input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" required className="w-full p-3 bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    <button type="submit" className="w-full bg-brand-pink hover:bg-brand-pink-hover text-white font-bold py-3 px-6 rounded-lg transition duration-300">
                        Create Account
                    </button>
                </form>
            </div>
            <p className="text-center text-sm text-gray-500 mt-6">
                Already have an account?{' '}
                <button onClick={() => handleSwitchMode('login')} className="font-semibold text-brand-pink hover:underline">
                    Log in
                </button>
            </p>
        </>
    );

    const renderSocialConfirmStep = () => (
        <>
            <div className="text-center">
                {pendingUser?.profilePic ? (
                    <img src={pendingUser.profilePic} alt="Profile" className="w-24 h-24 rounded-full mx-auto mb-4 border-4 border-brand-pink shadow-lg" />
                ) : (
                    <div className="w-24 h-24 rounded-full bg-gray-200 flex items-center justify-center mx-auto mb-4 border-4 border-gray-300">
                        <UserIcon className="w-16 h-16 text-gray-400" />
                    </div>
                )}
                <h2 className="text-2xl font-bold text-brand-text-dark">Connecting as {pendingUser?.name}</h2>
                <p className="text-gray-600 mt-1">{pendingUser?.email}</p>
            </div>
            <div className="mt-8 space-y-4">
                <p className="text-xs text-center text-gray-500 px-4">
                    By continuing, you confirm you have read and agree to AURA's <a href="#" className="underline hover:text-brand-pink">Terms of Service</a> and <a href="#" className="underline hover:text-brand-pink">Privacy Policy</a>.
                </p>
                <button onClick={() => setStep('age')} className="w-full bg-brand-pink hover:bg-brand-pink-hover text-white font-bold py-3 px-6 rounded-lg transition duration-300">
                    Continue to Final Step
                </button>
            </div>
            <div className="mt-6 text-center">
                <button onClick={() => { resetFormState(); setMode('register'); }} className="text-sm text-gray-500 hover:text-brand-pink hover:underline">
                    Use a different account
                </button>
            </div>
        </>
    );
    
    const renderAgeStep = () => (
        <>
            <div className="text-center">
                 {pendingUser?.profilePic && (
                    <img src={pendingUser.profilePic} alt="Profile" className="w-16 h-16 rounded-full mx-auto mb-4 border-2 border-brand-pink" />
                )}
                <h2 className="text-3xl font-bold text-brand-pink">Verify Your Age</h2>
                <p className="text-gray-600 mt-2">One last step, {pendingUser?.name}. Please enter your date of birth.</p>
            </div>
            <div className="mt-8 space-y-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Date of Birth</label>
                    <div className="flex gap-4">
                        <input type="text" value={dob.day} onChange={(e) => setDob({ ...dob, day: e.target.value.replace(/\D/g, '').slice(0, 2) })} placeholder="DD" className="w-full p-3 text-center bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                        <input type="text" value={dob.month} onChange={(e) => setDob({ ...dob, month: e.target.value.replace(/\D/g, '').slice(0, 2) })} placeholder="MM" className="w-full p-3 text-center bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                        <input type="text" value={dob.year} onChange={(e) => setDob({ ...dob, year: e.target.value.replace(/\D/g, '').slice(0, 4) })} placeholder="YYYY" className="w-full p-3 text-center bg-gray-50 rounded border border-gray-300 focus:ring-brand-pink focus:border-brand-pink" />
                    </div>
                </div>
                {dobError && <p className="text-sm text-red-600 text-center">{dobError}</p>}
                <div>
                    <button onClick={handleAgeVerification} className="w-full bg-brand-pink hover:bg-brand-pink-hover text-white font-bold py-3 px-6 rounded-lg transition duration-300">
                        Complete Registration
                    </button>
                </div>
            </div>
            <div className="mt-4 text-center">
                <button 
                    onClick={() => {
                        setDobError(null);
                        // If user came from social login, go back to confirmation. Otherwise, back to details.
                        if (pendingUser?.profilePic) {
                            setStep('social_confirm');
                        } else {
                            setStep('details');
                        }
                    }} 
                    className="text-sm text-gray-500 hover:text-brand-pink hover:underline"
                >
                    Back
                </button>
            </div>
        </>
    );

    const renderContent = () => {
        if (mode === 'login') {
            return renderLoginView();
        }
        // mode is 'register'
        switch (step) {
            case 'details':
                return renderRegisterView();
            case 'social_confirm':
                return renderSocialConfirmStep();
            case 'age':
                return renderAgeStep();
            default:
                return renderRegisterView();
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-70 backdrop-blur-sm" onClick={closeLoginModal}>
            <div className="bg-white p-8 rounded-lg shadow-2xl max-w-md w-full mx-4 transform transition-all" onClick={handleModalContentClick}>
                {renderContent()}
            </div>
        </div>
    );
};

export default LoginModal;
